version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"  # Puerto de MongoDB
    volumes:
      - mongo-data:/data/db  # Persistencia de datos en MongoDB
    networks:
      - hospital-network

  springboot-app:
    build: .
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"  # Puerto de la aplicación
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/hospitaldb
    depends_on:
      - mongo  # Espera que el contenedor de MongoDB se inicie antes de ejecutar
    networks:
      - hospital-network

volumes:
  mongo-data:

networks:
  hospital-network:
    driver: bridge
